name: pytorch-deepdream
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.10.11
  - pip==23.1.2
  - matplotlib
  - pytorch==2.0.0
  - torchvision==0.15.0
  - pip:
    - numpy
    - scipy
    - opencv-python>=4.7.0
    - imageio==2.30.0
    # - jupyter==
